Repository Azure/azure-functions-durable-extension, pull requests merged in 2018-11, with the labels that each got.

#490 Add option to avoid retrieving orchestration instance inputs
  src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
  src/WebJobs.Extensions.DurableTask/DurableOrchestrationClientBase.cs
  src/WebJobs.Extensions.DurableTask/DurableOrchestrationStatus.cs
  src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
  src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
  test/Common/DurableOrchestrationClientMock.cs
  test/Common/DurableTaskEndToEndTests.cs
  test/Common/TestOrchestratorClient.cs
Labels: enhancement

#494 Adding support for DurableActivityContextBase
  samples/VSSample.Tests/HelloSequenceActivityTests.cs
  samples/VSSample.Tests/HelloSequenceOrchestratorTests.cs
  samples/VSSample.Tests/HttpStartTests.cs
  samples/precompiled/HelloSequence.cs
  src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs
  src/WebJobs.Extensions.DurableTask/DurableActivityContext.cs
  src/WebJobs.Extensions.DurableTask/DurableActivityContextBase.cs
  src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
  test/Common/DurableTaskEndToEndTests.cs
  test/Common/TestActivities.cs
Labels: full-ci

#498 Adding new Purging History API-s
  src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
  src/WebJobs.Extensions.DurableTask/DurableOrchestrationClientBase.cs
  src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
  test/Common/DurableTaskEndToEndTests.cs
  test/Common/HttpApiHandlerTests.cs
  test/Common/TestOrchestrations.cs
Labels: full-ci

#503 Adding support for configuring task hub name from application settings
  src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
  src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
Labels: enhancement, full-ci

#514 Adding support for deterministic GUID
  src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
  src/WebJobs.Extensions.DurableTask/DurableOrchestrationContextBase.cs
  src/WebJobs.Extensions.DurableTask/GuidManager.cs
  src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
  test/Common/DurableTaskEndToEndTests.cs
  test/Common/TestOrchestrations.cs
  test/FunctionsV2/GuidManagerTests.cs
Labels: full-ci

#513 Adding support for configuring Task Hub Name via OrchestrationClientAttribute
  src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs
  src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
  src/WebJobs.Extensions.DurableTask/OrchestrationClientAttribute.cs
  test/Common/ClientFunctions.cs
  test/Common/DurableTaskEndToEndTests.cs
  test/Common/DurableTaskHostExtensions.cs
  test/Common/DurableTaskLifeCycleNotificationTest.cs
  test/Common/HttpApiHandlerTests.cs
  test/Common/TestHelpers.cs
Labels: full-ci

#517 Feature/511 waitforexternalevent nongeneric
  CONTRIBUTING.md
  src/WebJobs.Extensions.DurableTask/DurableOrchestrationClientBase.cs
  src/WebJobs.Extensions.DurableTask/DurableOrchestrationContextBase.cs
  src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
  test/Common/DurableTaskEndToEndTests.cs
  test/Common/TestOrchestrations.cs
  test/Common/TestOrchestratorClient.cs
Labels: full-ci

#528 Adding support for source-link
  src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
  src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
  src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
Labels: full-ci
