Repository Azure/azure-functions-durable-extension, pull requests merged in 2019-03, with the labels that each got.

#628 Mark Serializable to FunctionFailedException
  src/WebJobs.Extensions.DurableTask/FunctionFailedException.cs
Labels: full-ci

#627 Allow to configure max polling interval via host.json
  src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
  src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
  src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
  test/Common/TestHelpers.cs
  test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
  test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
Labels: full-ci

#639 Added TrackingStoreConnectionStringName and TrackingStoreNamePrefix settings
  src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
  src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
Labels: enhancement

#638 Opt-out of specific lifecycle events that are published to Event Grid
  src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
  src/WebJobs.Extensions.DurableTask/EventGridLifeCycleNotificationHelper.cs
  src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
  test/Common/DurableTaskLifeCycleNotificationTest.cs
  test/Common/TestHelpers.cs
Labels: enhancement, full-ci

#663 initial implementation of durable actors for v2
  src/WebJobs.Extensions.DurableTask/ActorScheduler/ActorId.cs
  src/WebJobs.Extensions.DurableTask/ActorScheduler/LockingRulesViolationException.cs
  src/WebJobs.Extensions.DurableTask/ActorScheduler/OperationMessage.cs
  src/WebJobs.Extensions.DurableTask/ActorScheduler/ResponseMessage.cs
  src/WebJobs.Extensions.DurableTask/ActorScheduler/SchedulerState.cs
  src/WebJobs.Extensions.DurableTask/ActorScheduler/TypedStateView.cs
  src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs
  src/WebJobs.Extensions.DurableTask/Bindings/ActorTriggerAttributeBindingProvider.cs
  src/WebJobs.Extensions.DurableTask/Bindings/BindingHelper.cs
  src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableActivityContext.cs
  src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableActorContext.cs
  src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableCommonContext.cs
  src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationClient.cs
  src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs
  src/WebJobs.Extensions.DurableTask/ContextInterfaces/DurableContextExtensions.cs
  src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDeterministicExecutionContext.cs
  src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableActivityContext.cs
  src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableActorContext.cs
  src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs
  src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationContext.cs
  src/WebJobs.Extensions.DurableTask/ContextInterfaces/IInterleavingActorContext.cs
  src/WebJobs.Extensions.DurableTask/ContextInterfaces/IInterleavingContext.cs
  src/WebJobs.Extensions.DurableTask/ContextInterfaces/IStateView.cs
  src/WebJobs.Extensions.DurableTask/DurableActivityContext.cs
  src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
  src/WebJobs.Extensions.DurableTask/DurableOrchestrationContextBase.cs
  src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
  src/WebJobs.Extensions.DurableTask/FunctionType.cs
  src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs
  src/WebJobs.Extensions.DurableTask/Listener/DurableTaskListener.cs
  src/WebJobs.Extensions.DurableTask/Listener/TaskActorShim.cs
  src/WebJobs.Extensions.DurableTask/Listener/TaskCommonShim.cs
  src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
  src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs
  src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
  src/WebJobs.Extensions.DurableTask/TriggerAttributes/ActivityTriggerAttribute.cs
  src/WebJobs.Extensions.DurableTask/TriggerAttributes/ActorTriggerAttribute.cs
  src/WebJobs.Extensions.DurableTask/TriggerAttributes/OrchestrationTriggerAttribute.cs
  test/Common/ClientFunctions.cs
  test/Common/DurableContextExtensionsTests.cs
  test/Common/DurableOrchestrationClientBaseTests.cs
  test/Common/DurableOrchestrationClientMock.cs
  test/Common/DurableOrchestrationContextBaseTests.cs
  test/Common/DurableTaskEndToEndTests.cs
  test/Common/HttpApiHandlerTests.cs
  test/Common/TestActivities.cs
  test/Common/TestActors.cs
  test/Common/TestHelpers.cs
  test/Common/TestOrchestrations.cs
  test/Common/TestOrchestratorClient.cs
Labels: full-ci
